{+forward-override{forward-socks5 127.0.0.1:1080 .}}
91.108.56.150
149.154.175.50
.du9l.com
.docs.com
.ephen.me
.ttionya.com
.rsshub.app
.baizihan.me
.opensource.com
.gog.com
.rise.ph
.pgp.net
.tt-rss.org
.linux.com
f-droid.org
blessing.studio
.appinn.com
.kali.org
.pressablecdn.com
.pressable.com
.feedburner.com
.google.com
.twitter.com
.youtube.com
.privoxy.org
t.co
.reddit.com
.doubibackup.com
.co.uk
.naver.com
.microsoft.com
.libreoffice.org
.yahoo.com
.goo.gl
.lithium.com
.golang.org
.googlesource.com
.fuchsia.dev
.gstatic.com
fuchsia.dev
.wp.com
.dropboxstatic.com
.ptwxz.com
.tujidao.com
.fontawesome.com
.studiofow.com
.unrealengine.com
.everesttech.net
.ooyala.com
.nintendo.net
.treasuredata.com
.nintendo.com
.geetest.com
.bizible.com
.mongodb.org
.gravuregirlz.com
.sharepoint.com
.162rr.com
.adf.ly
.donmai.us
.pstatic.net
.inoreader.com
.oracle.com
.gameguardian.net
.discordapp.com
.ubuntu.com
.pornhub.com
.trafficjunky.net
.phncdn.com
.baletingo.com
.archive.is
.mtime.com
.github.com
.live.com
.gitlab.com
.indiegala.com
.dbkoda.com
.puri.sm
.ljason.cn
.techglobex.net
.bootstrapcdn.com
.jquery.com
.indiegalacdn.com
.5down.net
.adnxs.com
.adsrvr.org
.aixifan.com
.akamaihd.net
.amazon.com
.amazonaws.com
.android.com
.anquan.org
.artstation.com
.askubuntu.com
.aspnetcdn.com
.assrt.net
.asuswebstorage.com
.atom.io
.atombase.com
.barilliance.com
.bing.com
.bit.ly
.blog.google
.blogblog.com
.blogger.com
.blogspot.tw
.bootcss.com
.bp.blogspot.com
.cannedbanners.com
.cdninstagram.com
.cdnst.net
.change.org
.chinagfw.org
.cldup.com
.cloudflare.com
.cloudfront.net
.cloudup.com
.com.hk
.creativemarket.com
.crwdcntrl.net
.disqus.com
.disquscdn.com
.djangoproject.com
.docker.com
.doub.io
.dropbox.com
.dropboxusercontent.com
.etcher.io
.fastly.net
.fbcdn.net
.freefilesync.org
.fullstory.com
.g.co
.gamepedia.com
.getpocket.com
.ggpht.com
.gitbooks.io
.github.io
.githubapp.com
.githubusercontent.com
.giveaway.su
.gnome-look.org
.gogs.io
.googleapis.com
.googleblog.com
.googlecode.com
.googlesyndication.com
.googleusercontent.com
.googlevideo.com
.gravatar.com
.greasyfork.org
.hexagon-analytics.com
.histats.com
.howtogeek.com
.humblebundle.com
.imgix.net
.imgur.com
.instagram.com
.interoute.net
.jenniferbland.com
.jetbrains.com
.jsdelivr.net
.krxd.net
.laod.cn
.linezing.com
.linuxdiyf.com
.macnwins.com
.makeding.com
.mariadb.org
.material.io
.mediafire.com
.medium.com
.minixiazai.com
.mixpanel.com
.momentcdn.net
.mongodb.com
.msecnd.net
.msn.com
.mxpnl.com
.mysql.com
.mzstatic.com
.nanqinlang.com
.netdna-ssl.com
.netease.com
.netflix.com
.nflxext.com
.nflxvideo.net
.nocookie.net
.nodejs.org
.npmjs.org
.offcloud.com
.letscorp.net
.oktraf.ru
.oneclickroot.com
.opendesktop.org
.optimizely.com
.orbital-apps.com
.outbrain.com
.packtpub.com
.petametrics.com
.pinimg.com
.pinterest.com
.pixiv.net
.pixnet.net
.pling.com
.plurk.com
.polygon.com
.prfct.co
.pscp.tv
.pubnub.com
.qtsdatacenters.com
.quantcount.com
.quantserve.com
.raspberrypi.org
.rawgit.com
.readthedocs.org
.redditstatic.com
.reviewgeek.com
.s-microsoft.com
.scorecardresearch.com
.segment.io
.sex8.cc
.sharethis.com
.skyts.net
.softasm.com
.ssl-images-amazon.com
.sstatic.net
.ssucclub.pw
.staticfile.org
.steamcommunity.com
.steampowered.com
.steamstatic.com
.suntechspeedtest.com
.t.me
.tapad.com
.tdesktop.com
.telegram.org
.telesco.pe
.tiobe.com
.torproject.org
.tumblr.com
.turn.com
.tvfiles.net
.twimg.com
.typekit.net
.typography.com
.us.to
.usenet.nl
.vinahost.vn
.visualwebsiteoptimizer.com
.vox-cdn.com
.voxmedia.com
.vscode-update.azurewebsites.net
.vuejs.org
.w3schools.com
.website-solution.net
.wikipedia.org
.wilsoninfo.com
.windows.net
.woobox.com
.wordpress.com
.xda-cdn.com
.xuite.net
.xx
.blogspot.com
.you-get.org
.youtu.be
.ytimg.com
.zbrushcn.com
.zdbb.net
.zeronet.io
