{+forward-override{forward-socks5 127.0.0.1:1080 .}}
.162rr.com
.5down.net
.adf.ly
.adnxs.com
.adsrvr.org
.aixifan.com
.akamaihd.net
.alpinelinux.org
.amazon.com
.amazonaws.com
.android.com
.anquan.org
.appinn.com
.apprcn.com
.archive.is
.ari-maj.com
.artstation.com
.askubuntu.com
.aspnetcdn.com
.assrt.net
.asuswebstorage.com
.atom.io
.atombase.com
.avgle.com
.baizihan.me
.baletingo.com
.barilliance.com
.bing.com
.bit.ly
.bizible.com
.blog.google
.blogblog.com
.blogger.com
.blogspot.com
.blogspot.tw
.bootcss.com
.bootstrapcdn.com
.bp.blogspot.com
.cannedbanners.com
.cdninstagram.com
.cdnst.net
.change.org
.chinagfw.org
.cldup.com
.cloudflare.com
.cloudfront.net
.cloudup.com
.co.jp
.co.uk
.com.hk
.com.tw
.creativemarket.com
.crwdcntrl.net
.dbkoda.com
.discord.gg
.discord.media
.discordapp.com
.discordapp.net
.disqus.com
.disquscdn.com
.djangoproject.com
.docker.com
.docs.com
.donmai.us
.doub.io
.doubibackup.com
.dropbox.com
.dropboxstatic.com
.dropboxusercontent.com
.du9l.com
.ephen.me
.etcher.io
.everesttech.net
.fastly.net
.fau.de
.fbcdn.net
.feedburner.com
.fontawesome.com
.freefilesync.org
.fuchsia.dev
.fullstory.com
.g.co
.gameguardian.net
.gamepedia.com
.geetest.com
.getpocket.com
.ggpht.com
.gitbooks.io
.github.com
.github.io
.githubapp.com
.githubusercontent.com
.gitlab.com
.giveaway.su
.gnome-look.org
.gog.com
.gogs.io
.golang.org
.golangtc.com
.goo.gl
.google.cn
.google.com
.googleapis.com
.googleblog.com
.googlecode.com
.googlesource.com
.googlesyndication.com
.googleusercontent.com
.googlevideo.com
.gravatar.com
.gravuregirlz.com
.greasyfork.org
.gstatic.com
.gvt1.com
.hexagon-analytics.com
.histats.com
.howtogeek.com
.humblebundle.com
.ibm.com
.imgix.net
.imgur.com
.indiegala.com
.indiegalacdn.com
.inoreader.com
.instagram.com
.interoute.net
.javbus.com
.jenniferbland.com
.jetbrains.com
.jquery.com
.jsdelivr.net
.kali.org
.krxd.net
.laod.cn
.letscorp.net
.librehat.com
.libreoffice.org
.linezing.com
.linux.com
.linuxdiyf.com
.lithium.com
.live.com
.ljason.cn
.macnwins.com
.makeding.com
.mariadb.org
.material.io
.mediafire.com
.medium.com
.microsoft.com
.minixiazai.com
.mixpanel.com
.momentcdn.net
.mongodb.com
.mongodb.org
.msecnd.net
.msn.com
.mtime.com
.mxpnl.com
.mysql.com
.mzstatic.com
.nanqinlang.com
.naver.com
.netdna-ssl.com
.netease.com
.netflix.com
.nflxext.com
.nflxvideo.net
.nintendo.com
.nintendo.net
.nocookie.net
.nodejs.org
.npmjs.org
.offcloud.com
.oktraf.ru
.oneclickroot.com
.ooyala.com
.opendesktop.org
.opensource.com
.optimizely.com
.oracle.com
.orbital-apps.com
.outbrain.com
.packtpub.com
.petametrics.com
.pgp.net
.phncdn.com
.pinimg.com
.pinterest.com
.pixelexperience.org
.pixiv.net
.pixnet.net
.pling.com
.plurk.com
.polygon.com
.pornhub.com
.pressable.com
.pressablecdn.com
.prfct.co
.privoxy.org
.pscp.tv
.pstatic.net
.ptwxz.com
.pubnub.com
.puri.sm
.pythonhosted.org
.qtsdatacenters.com
.quantcount.com
.quantserve.com
.raspberrypi.org
.rawgit.com
.readthedocs.org
.reddit.com
.redditstatic.com
.reviewgeek.com
.rise.ph
.rsshub.app
.s-microsoft.com
.scorecardresearch.com
.segment.io
.servimg.com
.sex8.cc
.sharepoint.com
.sharethis.com
.skyts.net
.softasm.com
.ssl-images-amazon.com
.sstatic.net
.ssucclub.pw
.stackoverflow.com
.staticfile.org
.steamcommunity.com
.steampowered.com
.steamstatic.com
.studiofow.com
.suntechspeedtest.com
.t.me
.tapad.com
.tdesktop.com
.techglobex.net
.telegram.org
.telesco.pe
.tiobe.com
.torproject.org
.trafficjunky.net
.treasuredata.com
.tt-rss.org
.ttionya.com
.tujidao.com
.tumblr.com
.turn.com
.tvfiles.net
.twimg.com
.twitter.com
.typekit.net
.typography.com
.ubi.com
.ubisoft.com
.ubuntu.com
.unity.com
.unity3d.com
.unrealengine.com
.us.to
.usenet.nl
.vinahost.vn
.visualstudio.com
.visualwebsiteoptimizer.com
.vox-cdn.com
.voxmedia.com
.vscode-update.azurewebsites.net
.vuejs.org
.w3schools.com
.website-solution.net
.wikipedia.org
.wilsoninfo.com
.windows.net
.woobox.com
.wordpress.com
.wp.com
.xda-cdn.com
.xuite.net
.xvideos.com
.xx
.yahoo.com
.you-get.org
.youtu.be
.youtube.com
.ytimg.com
.zbrushcn.com
.zdbb.net
.zeronet.io
104.238.198.186
107.174.238.55
133.130.108.127
149.154.175.50
149.202.60.146
158.69.62.21
163.172.140.46
163.172.180.68
163.172.81.35
164.132.200.122
173.254.204.71
178.175.143.27
91.108.56.150
chelpus.com
f-droid.org
fuchsia.dev
saber.love
t.co